// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var about = `Malak Abd-ElHamid \u2014 Artificial Intelligence Graduate from Helwan International Technological University (HITU), 2022\u20132026.

Focused on Machine Learning, Computer Vision, and NLP with hands-on experience building end-to-end AI applications. Featured projects include EyeSpeak (AI-powered eye tracking on Raspberry Pi), VisionWalk (YOLOv5 pedestrian detection), and Calibra8 (industrial LLM chatbot with FastAPI and MySQL).

Currently a Machine Learning Intern at the Digital Egypt Pioneers Initiative (DEPI), with prior AI & Business training at Commercial International Bank (CIB).

Core stack: Python, FastAPI, TensorFlow, Keras, OpenCV, Scikit-Learn, Pandas, NumPy, YOLOv5, MySQL.`;
var get_about_default = defineTool({
  name: "get_about",
  title: "Get about / bio",
  description: "Returns a short biography and professional summary for Malak Mohamed.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: about }] })
});

// src/lib/mcp/tools/get-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var categories = {
  programming: ["Python", "Java"],
  ai: ["Machine Learning", "Deep Learning", "Computer Vision", "Natural Language Processing"],
  backend: ["FastAPI", "REST APIs"],
  database: ["SQL", "MySQL"],
  libraries: ["TensorFlow", "Keras", "OpenCV", "Scikit-Learn", "Pandas", "NumPy", "YOLOv5"],
  tools: ["Git", "GitHub", "VS Code", "Raspberry Pi", "Microsoft Office"]
};
var soft = ["Communication", "Teamwork", "Fast Learner", "Flexible and Adaptable"];
var get_skills_default = defineTool2({
  name: "get_skills",
  title: "Get skills",
  description: "Returns Malak's technical skills (with proficiency levels) and soft skills.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const text = Object.entries(categories).map(([k, v]) => `${k[0].toUpperCase() + k.slice(1)}:
` + v.map((s) => `- ${s}`).join("\n")).join("\n\n") + "\n\nSoft skills:\n" + soft.map((s) => `- ${s}`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { ...categories, soft }
    };
  }
});

// src/lib/mcp/tools/get-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var projects = [
  {
    title: "EyeSpeak",
    description: "AI-powered eye tracking system for hands-free interaction using Computer Vision and Machine Learning on Raspberry Pi Zero 2 W. Achieved 87% gaze estimation accuracy.",
    github: "https://github.com/Malakabdelhamid/EyeSpeak",
    tech: ["Python", "OpenCV", "Random Forest", "Raspberry Pi", "Android", "IoT"]
  },
  {
    title: "Calibra8 AI Chatbot",
    description: "Industrial AI chatbot combining LLMs, semantic search, and product recommendations built with FastAPI, Ollama, and MySQL.",
    tech: ["Python", "FastAPI", "Ollama", "MySQL", "LLMs"]
  },
  {
    title: "VisionWalk",
    description: "Real-time pedestrian detection using YOLOv5 and OpenCV trained on the Caltech Pedestrian Dataset. Achieved 80% accuracy.",
    github: "https://github.com/Malakabdelhamid/VisionWalk",
    demo: "/vision.mp4",
    tech: ["Python", "YOLOv5", "OpenCV", "TensorFlow"]
  },
  {
    title: "Sign Language Translator",
    description: "Smart gloves powered by ML that translate sign language into text using flex sensors and ESP32.",
    github: "https://github.com/Malakabdelhamid/Sign-Language-Translator",
    demo: "/gloves.mp4",
    tech: ["Python", "Random Forest", "ESP32", "Flutter"]
  },
  {
    title: "Heart Disease Prediction",
    description: "ML model predicting heart disease risk from patient medical data.",
    github: "https://github.com/Malakabdelhamid/Heart-Disease-Prediction",
    tech: ["Python", "Scikit-Learn", "Pandas"]
  },
  {
    title: "Earthquake Prediction",
    description: "ML model for earthquake prediction and seismic data analysis.",
    github: "https://github.com/Malakabdelhamid/Earthquake-Prediction",
    tech: ["Python", "Machine Learning", "Pandas", "NumPy"]
  }
];
var get_projects_default = defineTool3({
  name: "get_projects",
  title: "Get projects",
  description: "Returns Malak's featured portfolio projects with descriptions and demo links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: projects.map(
          (p) => `${p.title}
${p.description}` + (p.tech ? `
Tech: ${p.tech.join(", ")}` : "") + (p.github ? `
GitHub: ${p.github}` : "") + (p.demo ? `
Demo: ${p.demo}` : "")
        ).join("\n\n")
      }
    ],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var contact = {
  email: "malakabdelhamid6@gmail.com",
  linkedin: "https://www.linkedin.com/in/malakabdelhamid1/",
  github: "https://github.com/Malakabdelhamid",
  portfolio: "https://malak-portfolio-five.vercel.app/"
};
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "Get contact info",
  description: "Returns Malak's public contact details: email, LinkedIn, and GitHub.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `Email: ${contact.email}
LinkedIn: ${contact.linkedin}
GitHub: ${contact.github}
Portfolio: ${contact.portfolio}`
      }
    ],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "malak-portfolio-mcp",
  title: "Malak Mohamed \u2014 Portfolio MCP",
  version: "0.1.0",
  instructions: "Public tools that expose Malak Mohamed's portfolio: bio, skills, projects, and contact info. All tools are read-only and require no authentication.",
  tools: [get_about_default, get_skills_default, get_projects_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
