// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var about = `Malak Mohamed \u2014 AI student and ML developer.

Passionate about end-to-end workflows: data preparation, exploratory data analysis, baseline modeling, and thorough evaluation. Currently part of the DEPI national ML internship with comprehensive training in machine learning, deep learning fundamentals, and modern AI techniques.

Core skills: Python, data cleaning, exploratory data analysis, and building scikit-learn pipelines.

Professional approach: clear and honest communication, conservative timelines, well-documented tidy notebooks, and open to feedback for continuous improvement.`;
var get_about_default = defineTool({
  name: "get_about",
  title: "Get about / bio",
  description: "Returns a short biography and professional summary for Malak Mohamed.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: about }] })
});

// src/lib/mcp/tools/get-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var technical = [
  { name: "Python", level: 90 },
  { name: "Data Preparation & EDA", level: 88 },
  { name: "Machine Learning", level: 85 },
  { name: "Pandas", level: 85 },
  { name: "Scikit-learn", level: 75 },
  { name: "NumPy", level: 85 },
  { name: "Deep Learning", level: 60 },
  { name: "Computer Vision", level: 50 }
];
var soft = [
  "Communication",
  "Teamwork",
  "Fast Learner",
  "Leadership",
  "Flexible and adaptable"
];
var get_skills_default = defineTool2({
  name: "get_skills",
  title: "Get skills",
  description: "Returns Malak's technical skills (with proficiency levels) and soft skills.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const text = "Technical skills:\n" + technical.map((s) => `- ${s.name} (${s.level}%)`).join("\n") + "\n\nSoft skills:\n" + soft.map((s) => `- ${s}`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { technical, soft }
    };
  }
});

// src/lib/mcp/tools/get-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var projects = [
  {
    title: "VisionWalk",
    description: "AI-powered pedestrian detection system using computer vision to enhance urban safety and traffic management.",
    demo: "/vision.mp4"
  },
  {
    title: "EgGuide",
    description: "VR-based tourism platform showcasing Egyptian landmarks with immersive virtual reality experiences."
  },
  {
    title: "Sign Language Translator",
    description: "Smart gloves powered by IoT and machine learning that translate sign language into text, bridging communication for the deaf and dumb community.",
    demo: "/gloves.mp4"
  }
];
var get_projects_default = defineTool3({
  name: "get_projects",
  title: "Get projects",
  description: "Returns Malak's featured portfolio projects with descriptions and demo links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: projects.map((p) => `${p.title}
${p.description}${p.demo ? `
Demo: ${p.demo}` : ""}`).join("\n\n")
      }
    ],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var contact = {
  email: "malakabdelhamid6@example.com",
  linkedin: "https://www.linkedin.com/in/malakabdelhamid1/",
  github: "https://github.com/Malakabdelhamid"
};
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "Get contact info",
  description: "Returns Malak's public contact details: email, LinkedIn, and GitHub.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: `Email: ${contact.email}
LinkedIn: ${contact.linkedin}
GitHub: ${contact.github}`
      }
    ],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "malak-portfolio-mcp",
  title: "Malak Mohamed \u2014 Portfolio MCP",
  version: "0.1.0",
  instructions: "Public tools that expose Malak Mohamed's portfolio: bio, skills, projects, and contact info. All tools are read-only and require no authentication.",
  tools: [get_about_default, get_skills_default, get_projects_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
